In [2]:
from noaa_ghcn import GHCN
import shapely

In [3]:
ghcn = GHCN()

lat_min = 7.0
lat_max = 37.0
lon_min = 65.0
lon_max = 97.0


import datetime as dt
inventory_subset = ghcn.filter_inventory(start_date= dt.datetime(2010, 1, 1), end_date=dt.datetime(2025, 1, 31))


inventory_subset = inventory_subset[
    (inventory_subset['LATITUDE'] >= lat_min) & (inventory_subset['LATITUDE'] <= lat_max) &
    (inventory_subset['LONGITUDE'] >= lon_min) & (inventory_subset['LONGITUDE'] <= lon_max)
]
inventory_subset

,ID,LATITUDE,LONGITUDE,ELEMENT,FIRSTYEAR,LASTYEAR,geometry,start_date,end_date
44,AFM00040948,34.566,69.212,TMAX,1966,2021,POINT (69.212 34.566),2010-01-01,2021-12-31
45,AFM00040948,34.566,69.212,TMIN,1967,2021,POINT (69.212 34.566),2010-01-01,2021-12-31
46,AFM00040948,34.566,69.212,PRCP,1983,2021,POINT (69.212 34.566),2010-01-01,2021-12-31
47,AFM00040948,34.566,69.212,SNWD,1974,2018,POINT (69.212 34.566),2010-01-01,2018-12-31
49,AFM00040990,31.500,65.850,TMAX,1973,2020,POINT (65.85 31.5),2010-01-01,2020-12-31
...,...,...,...,...,...,...,...,...,...
163250,PKM00041768,25.517,69.783,TMIN,1957,2025,POINT (69.783 25.517),2010-01-01,2025-01-31
163251,PKM00041768,25.517,69.783,PRCP,1957,2025,POINT (69.783 25.517),2010-01-01,2025-01-31
163253,PKM00041780,24.907,67.161,TMAX,1942,2025,POINT (67.161 24.907),2010-01-01,2025-01-31
163254,PKM00041780,24.907,67.161,TMIN,1942,2025,POINT (67.161 24.907),2010-01-01,2025-01-31
163255,PKM00041780,24.907,67.161,PRCP,1942,2025,POINT (67.161 24.907),2010-01-01,2025-01-31

In [4]:
inventory_subset.to_csv('/Datastorage/saptarishi.dhanuka_asp25/noaa_ghcn_meta.csv')

In [4]:


import time

tik = time.time()


print("Starting download")

df = ghcn.load_data(inventory_subset)


tok = time.time()

print(f"Download took: {tok - tik}")
df.head()

Starting download

Downloading data: 100%|██████████| 584/584 [00:09<00:00, 63.92file/s]

Download took: 160.28420305252075

            ID       DATE  DATA_VALUE M_FLAG Q_FLAG S_FLAG OBS_TIME ELEMENT
0  BGM00041859 2024-01-02        18.5   None   None      S     None    TMAX
1  BGM00041859 2024-01-04        26.4   None   None      S     None    TMAX
2  BGM00041859 2024-01-07        25.6   None   None      S     None    TMAX
3  BGM00041859 2024-01-09        20.0   None   None      S     None    TMAX
4  BGM00041859 2024-01-10        18.0   None   None      S     None    TMAX

In [5]:
df

,ID,DATE,DATA_VALUE,M_FLAG,Q_FLAG,S_FLAG,OBS_TIME,ELEMENT
0,BGM00041859,2024-01-02,18.5,None,None,S,None,TMAX
1,BGM00041859,2024-01-04,26.4,None,None,S,None,TMAX
2,BGM00041859,2024-01-07,25.6,None,None,S,None,TMAX
3,BGM00041859,2024-01-09,20.0,None,None,S,None,TMAX
4,BGM00041859,2024-01-10,18.0,None,None,S,None,TMAX
...,...,...,...,...,...,...,...,...
133070,PKM00041780,2025-01-27,0.0,None,None,S,None,PRCP
133071,PKM00041780,2025-01-28,0.0,None,None,S,None,PRCP
133072,PKM00041780,2025-01-29,0.0,None,None,S,None,PRCP
133073,PKM00041780,2025-01-30,0.0,None,None,S,None,PRCP
133074,PKM00041780,2025-01-31,0.0,None,None,S,None,PRCP